# Generated by Django 5.0.4 on 2024-07-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkgallery',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
