# Generated by Django 5.1.2 on 2024-10-24 11:20

import FruitipediaExamPrep2.profiles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), FruitipediaExamPrep2.profiles.validators.FirstLetterValidator()])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), FruitipediaExamPrep2.profiles.validators.FirstLetterValidator()])),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(error_messages={'max_length': '*Password length requirements: 8 to 20 characters'}, max_length=20, validators=[FruitipediaExamPrep2.profiles.validators.CustomLengthValidator()])),
                ('image_url', models.URLField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, default=18, null=True)),
            ],
        ),
    ]
