# Generated by Django 5.1.2 on 2024-10-27 07:56

import FurryFunniesApp.authors.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[FurryFunniesApp.authors.validators.LetterValidator(), django.core.validators.MinLengthValidator(4)])),
                ('last_name', models.CharField(max_length=40, validators=[FurryFunniesApp.authors.validators.LetterValidator(), django.core.validators.MinLengthValidator(4)])),
                ('passcode', models.CharField(max_length=7, validators=[FurryFunniesApp.authors.validators.PassCodeValidator(6)])),
                ('pets_number', models.SmallIntegerField()),
                ('info', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
