# Generated by Django 5.0.4 on 2024-06-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_exercise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
