# Generated by Django 5.1.2 on 2024-10-23 07:34

import WorldOfSpeedAppExamPrep24022024.profiles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[WorldOfSpeedAppExamPrep24022024.profiles.validators.CustomMinLengthValidator(2), WorldOfSpeedAppExamPrep24022024.profiles.validators.CustomRegexValidator()])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(verbose_name=django.core.validators.MinValueValidator(21))),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
