# Generated by Django 5.1.1 on 2024-10-04 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('photos', '0002_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.photo'),
        ),
    ]
