from project.controller import Controller

cnt = Controller()
print(cnt.add_aquarium("FreshwaterAquarium", "Test Fresh"))
# print(cnt.add_aquarium("FreshwaterAquarium", " "))
print(cnt.add_aquarium("SaltwaterAquarium", "Test Salt"))
print(cnt.add_aquarium("NewwaterAquarium", "Test Salt"))
print(cnt.add_decoration("Plant"))
print(cnt.add_decoration("Plant"))
print(cnt.add_decoration("Plant"))
print(cnt.add_decoration("Plant"))
print(cnt.add_decoration("Ornament"))
print(cnt.add_decoration("Ornament"))
print(cnt.add_decoration("Ornament"))
print(cnt.add_decoration("Ornament"))
print(cnt.insert_decoration("Test Fresh", "Plant"))
print(cnt.insert_decoration("Test Fresh", "Ornament"))
print(cnt.insert_decoration("Test Salt", "Plant"))
print(cnt.insert_decoration("Test Salt", "Plant"))
print(cnt.insert_decoration("Test Salt", "Plant"))
print(cnt.insert_decoration("Test Salt", "Plant"))
print(cnt.insert_decoration("Test Salt", "Ornament"))
print(cnt.add_fish("Test Salt", "Ornament", "Test Fish", "Test Species", 5))
print(cnt.add_fish("Test Salt", "FreshwaterFish", "Test Fish", "Test Species", 5))
print(cnt.add_fish("Test Salt", "SaltwaterFish", "Test Fish", "Test Species", 5))
print(cnt.add_fish("Test Salt", "SaltwaterFish", "Test Fish 1", "Test Species", 5))
print(cnt.add_fish("Test Salt", "SaltwaterFish", "Test Fish 2", "Test Species", 5))
print(cnt.add_fish("Test Salt", "SaltwaterFish", "Test Fish 3", "Test Species", 5))
print(cnt.feed_fish("Test Salt"))
print(cnt.feed_fish("Test Fresh"))
print(cnt.calculate_value("Test Salt"))
print(cnt.calculate_value("Test Fresh"))
print(cnt.report())