# Generated by Django 5.0.4 on 2024-07-31 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date_played',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='location',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
