"""Add model Chef with relationship to Recipe

Revision ID: 084f8f586abb
Revises: 9573e9ba9093
Create Date: 2024-07-17 12:59:02.164926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084f8f586abb'
down_revision: Union[str, None] = '9573e9ba9093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
