"""Add model Chef with relationship to Recipe

Revision ID: 2ca06bd75265
Revises: bc7cc7117b18
Create Date: 2024-07-17 11:59:32.197923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca06bd75265'
down_revision: Union[str, None] = 'bc7cc7117b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipies', sa.Column('chef_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'recipies', 'chefs', ['chef_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipies', type_='foreignkey')
    op.drop_column('recipies', 'chef_id')
    # ### end Alembic commands ###
