"""Add model Chef with relationship to Recipe

Revision ID: 9573e9ba9093
Revises: 2ca06bd75265
Create Date: 2024-07-17 12:05:45.137123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9573e9ba9093'
down_revision: Union[str, None] = '2ca06bd75265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipies', 'chef_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipies', 'chef_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
