# Generated by Django 3.2.7 on 2024-07-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_auto_20240719_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fruits',
            new_name='Fruit',
        ),
    ]
