# Generated by Django 3.2.7 on 2024-07-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0003_rename_fruits_fruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='fruits.category'),
        ),
    ]
