# Generated by Django 5.0.4 on 2024-06-24 16:36

from django.db import migrations
def define_item_rarity(apps, schema_editor):
    item = apps.get_model('main_app', 'Item')
    items = item.objects.all()
    for item in items:
        if item.price <= 10:
            item.rarity = "Rare"
            # item.save()
        elif 11 <= item.price <= 20:
            item.rarity = "Very Rare"
            # item.save()
        elif 21 <= item.price <= 30:
            item.rarity = "Extremely Rare"
            # item.save()
        else:
            item.rarity = "Mega Rare"
            # item.save()
        item.objects.bulk_update(items, ['rarity'])


def reverse_item_rarity(apps, schema_editor):
    item = apps.get_model('main_app', 'Item')
    items = item.objects.all()
    for item in items:
        item.rarity = item._meta.get_field('rarity').default
        # item.save()
    item.objects.bulk_update(items, ['rarity'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_item_order_person_smartphone'),
    ]

    operations = [migrations.RunPython(define_item_rarity, reverse_code=reverse_item_rarity)
    ]
