# Generated by Django 5.0.4 on 2024-06-24 16:36

from django.db import migrations


def define_phone_price(apps, schema_editor):
    phone = apps.get_model('main_app', 'Smartphone')
    phones = phone.objects.all()
    for phone in phones:
        phone.price = len(phone.brand) * 120
        phone.save()


def reverse_phone_price(apps, schema_editor):
    phone = apps.get_model('main_app', 'Smartphone')
    phones = phone.objects.all()
    for phone in phones:
        phone.price = 0
        phone.save()


def define_phone_category(apps, schema_editor):
    phone = apps.get_model('main_app', 'Smartphone')
    phones = phone.objects.all()
    for phone in phones:
        if phone.price >= 750:
            phone.category = "Expensive"
            phone.save()
        else:
            phone.category = "Cheap"
            phone.save()


def reverse_phone_category(apps, schema_editor):
    phone = apps.get_model('main_app', 'Smartphone')
    phones = phone.objects.all()
    for phone in phones:
        phone.category = "No category"
        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_define_item_rarity'),
    ]

    operations = [migrations.RunPython(define_phone_price, reverse_code=reverse_phone_price),
                  migrations.RunPython(define_phone_category, reverse_code=reverse_phone_category)
    ]
