# Generated by Django 5.0.4 on 2024-06-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_define_person_age_group'),
        ('main_app', '0013_update_order'),
    ]

    operations = [
    ]
