# Generated by Django 5.0.4 on 2024-07-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subject',
            new_name='subjects',
        ),
    ]
