# Generated by Django 5.0.4 on 2024-07-02 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_studentenrollment_enrollment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('lecturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.lecturer')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('office_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
