# Generated by Django 5.1.2 on 2024-10-22 10:20

import TastyRecipesAppExamPrep17042024.profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True, validators=[TastyRecipesAppExamPrep17042024.profiles.validators.CustomMinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=30, validators=[TastyRecipesAppExamPrep17042024.profiles.validators.FirstLetterCapitalValidator()])),
                ('last_name', models.CharField(max_length=30, validators=[TastyRecipesAppExamPrep17042024.profiles.validators.FirstLetterCapitalValidator()])),
                ('chef', models.BooleanField(default=False)),
                ('bio', models.TextField()),
            ],
        ),
    ]
